### ISSUE TITLE
Roadmap Suggestions

### ISSUE THREAD

**Issue by cmuc24** [AlexSciFier/neonlink#13]
love your App! Great!
some points you can consider, or maybe u have it already on your list.... 
of course up to you if or if not.

- [ ] Frontend edit mode (links, groups, backgrounds, re-arrange, sort...)
- [ ] Drag & Drop functionality 
- [ ] links - manual icon upload 
   (for some reason, icons from some local services (ip+port) are not show )
- [ ] background videos. before i write to much, have a look here, https://manganum.app
- [ ] add Bookmark to neonlink button
   this button should show you a visual sign, if a link is already in the database

if i could, if i can help with some coding tasks, talk to me
i can, just a little bit more then string translations :-)

**Comment by AlexSciFier** [comment]
Hi! Thank for your suggestions.

 - As alternative to background videos i can suggest you to use webp animated image. The quality isn't great and it's laggy, but it works right now.
- Icons from local services works only in local network obviously. You can change icon url to same icon but in internet.
- In 1.2.3 the app gives you an error if bookmark is already exist.
- What do you mean by Drag & Drop functionality?
- "Frontend edit mode", again i doesnt quite understood this.

I don't want to overcomplicate the application. The Dashboard (main page with categories panels) shoud be simple, clean and static. For this i moved all edit functionality under settings tab.

**Comment by cmuc24** [comment]
- example for drag and drop functionality https://react-beautiful-dnd.netlify.app/
ReArrange Links or even groups without need to go to the backend
That includes the meaning of frontend editing. editing without need to go to the backend

To be with you and for simplify things, this could all packed in a simple "Edit Mode" Button on the frontend. 
Up to you, as always! Thanks for your time and neonlink :)
